### PR TITLE
Fixes EdlibAlignResult memory leak

### LINKED ISSUE #11: Memory leak on edlibAlign
Thanks for this nice piece of software! Besides the usefulness, I was curious about the nice TUI colors and navigating the source code i spot a suspicious call to what looked to be a C API that would lead to a memory leak.

In fact, the leak was confirmed on `edlibAlign`.

image

For the record, the screenshot is from heaptrack analyzing the memory profile of clang-unformat running against its own source code: `heaptrack ./build/clang-unformat --input standalone --output build/.clang-format`

### PR DESCRIPTION
**Pull request by cnihelton**
Hi Alan, thanks for this nice piece of software!

`edlib` README quite misleading in its first snipped of code suggesting a memory leak. Downwards it explains that the result of `edlibAlign` must be freed. See https://github.com/Martinsos/edlib#handling-result-of-edlibalign

It's a C API after all.
This PR wraps the `EdlibAlignResult` into a local struct to ensure calling `edlibFreeAlignResult` at scope exit.

The screenshot below shows `heaptrack` analyzing the output data of the `clang-unformat` program running with the same parameters mentioned in #3 .

Screenshot from 2023-02-05 07-56-48

Fixes #3

### CODE REVIEW

File: standalone/levenshtein.cpp [hunk 1]
```diff
@@ -9,15 +9,30 @@
...
 std::size_t
 levenshtein_distance(std::string_view s1, std::string_view s2) {
-    return edlibAlign(
-               s1.data(),
-               s1.size(),
-               s2.data(),
-               s2.size(),
-               edlibDefaultAlignConfig())
-        .editDistance;
+    return AlignResult{ s1, s2 }.editDistance();
```
Comment (alandefreitas) [inline standalone/levenshtein.cpp]: The semantics of `AlignResult` seems a little weird: `self` is public but `self.editDistance` is accessed through `editDistance()`, the operation takes place in the constructor of a result type, and so on...

Since the struct won't be reused, why not just call the canonical provided API directly here and call it a day:

```cpp
std::size_t
levenshtein_distance(std::string_view s1, std::string_view s2) {
    auto r = edlibAlign(
               s1.data(),
               s1.size(),
               s2.data(),
               s2.size(),
               edlibDefaultAlignConfig());
    std::size_t d = r.editDistance;
    edlibFreeAlignResult(r);
    return d;
}
```

**Review by alandefreitas — COMMENTED** [review]
Thanks for that!

File: standalone/levenshtein.cpp (hunk 1 above)
Comment (cnihelton) [reply standalone/levenshtein.cpp]: I was unsure about exceptions, but looking around in edlib source code it seems more likely to get a SIGSEGV than an exception. And your comment on semantics is relevant. I'll fix that.

Comment (alandefreitas) [reply standalone/levenshtein.cpp]: > I was unsure about exceptions, 

No exceptions in C :)

> but looking around in edlib source code it seems more likely to get a SIGSEGV than an exception. And your comment on semantics is relevant. I'll fix that.

Great. Did you check if the new version also fixes the original problem locally for you?

Comment (cnihelton) [reply standalone/levenshtein.cpp]: > > I was unsure about exceptions,
> 
> No exceptions in C :)

Indeed, we have `extern "C"` in the header. We also have `include <vector>` and what-not-else in the implementation file (which is cpp, ofc) but not a single `catch` clause anywhere. If any piece of implementation code throws an exception all bets are off. 😅 
Maybe I should take some time to learn the algorithms and propose some changes in edlib.

> > but looking around in edlib source code it seems more likely to get a SIGSEGV than an exception. And your comment on semantics is relevant. I'll fix that.
> 
> Great. Did you check if the new version also fixes the original problem locally for you?

Yeap! No mention to edlib in the memory leak section. The motivating issue is fixed.

image

**Comment by alandefreitas** [comment]
Thanks
